modLoader = "javafml"
loaderVersion = "${forge_loader_version_range}"
issueTrackerURL = "https://github.com/Crendgrim/SilentScreenshots/issues"
license = "LGPL-3.0"

[[mods]]
modId = "silentscreenshots"
version = "${mod_version}"
displayName = "Silent Screenshots"
authors = "Crendgrim"
description = '''
Removes the chat message after taking a screenshot
'''
logoFile = "silentscreenshots.png"
displayTest = "IGNORE_ALL_VERSION"

[[dependencies.silentscreenshots]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.silentscreenshots]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range_forge}"
ordering = "NONE"
side = "BOTH"
